apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: canary.log.run
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: runnable-kubernetes-pull-secret
          restartPolicy: Never
          containers:
          - name: canary-log-run
            image: quay.io/runnable/khronos:v6.5.12
            env:
              - name: DATADOG_HOST
                valueFrom:
                  fieldRef:
                    fieldPath: spec.nodeName
              - name: DATADOG_PORT
                value: "8125"
            args:
              - bash
              - -c
              - /khronos/bin/cli.js --queue canary.log.run --job '{}' --host rabbitmq:5672 --username o2mdLh9N9Ke2GzhoK8xsruYPhIQFN7iEL44dQJoq7OM --password wKK7g7NWKpQXEeSzyWB7mIpxZIL8H2mDSf3Q6czR3Vk
